---
#
#    Debian 7 (wheezy) Minimal System (docker-compose.yml)
#    Copyright (C) 2016-2017 Stafli
#    This file is part of the Stafli Application Stack.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# For Docker Compose v2+ only
version: '2'

#
# Main services
#
services:

  minimal:
    labels:
      - "org.label-schema.schema-version=1.0"
      - "org.label-schema.name=$PROJECT_NAME - Minimal service"
      - "org.label-schema.description=Based on $PROJECT_ORIGIN"
      - "org.label-schema.vendor=$PROJECT_VENDOR"
      - "org.label-schema.url=$PROJECT_URL"
      - "license=$PROJECT_LICENSE"
      - "org.label-schema.vcs-ref=$VCS_REF"
      - "org.label-schema.vcs-url=$VCS_URL"
      - "os-id=$OS_ID"
      - "os-version-id=$OS_VERSION_ID"
      - "architecture=$BUILD_ARCH"
      - "org.label-schema.version=$BUILD_VERSION"
      - "org.label-schema.build-date=$BUILD_DATE"
    image: "stafli/stafli.minimal.system:debian7_minimal"
    build:
      context: "./dockerfiles"
      dockerfile: "minimal.dockerfile"
      args:
        os_terminal: "linux"
        os_timezone: "Etc/UTC"
        os_locale: "en_GB"
        os_charset: "UTF-8"
    logging:
      driver: "json-file"
    working_dir: "/tmp"
    command: "/bin/bash"

#
# Networks
#
networks:
  default:
    driver: "bridge"

#
# Volumes
#
volumes:
  minimal_data:
    driver: "local"
